# Site settings
title: JustPeace Labs
email: info@justpeacelabs.org
description: > # this means to ignore newlines until "baseurl:"
  Innovative solutions for lasting peace

permalink: /blog/:year-:month-:day/:title/
feed: "/blog/atom.xml"

excerpt_separator: <!--more-->
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://justpeacelabs.org" # the base hostname & protocol for your site
twitter_username: justpeacelabs
#github_username:  jekyll
page_gen-dirs: true
page_gen:
  - data: 'site.data.contentful.spaces.site.2wKn6yEnZewu2SCCkus4as'
    template: 'post'
    name: 'slug'
    dir: 'blog'

# Build settings
markdown: kramdown
exclude: 
- Dockerfile
- .firebaserc
- .gitignore
- Gemfile
- Gemfile.lock
- docker-compose.yml
- firebase.json
- Makefile

excerpt_separator: <!--more-->
contentful:
  spaces:
    - site: # Jekyll _data folder identifier - Required
        space: 0p3n5dhw2rug         # Required
        access_token: 03cb6af64ba069b279c24e7a282020abea8f48e08febba7530383d07eb6e9851  # Required
        cda_query:                  # Optional
          include: 2
          limit: 100
          # content_type: 2wKn6yEnZewu2SCCkus4as
        # cda_query:                  # Optional
          # include: 2
          # limit: 100
        # all_entries: true           # Optional - Defaults to false, only grabbing the amount set on CDA Query
        # all_entries_page_size: 1000 # Optional - Defaults to 1000, maximum amount of entries per CDA Request for all_entries
        # content_types:              # Optional
        #   cat: 2wKn6yEnZewu2SCCkus4as
        # client_options:             # Optional
          # api_url: 'preview.contentful.com' # Defaults to 'api.contentful.com' which is Production
          # max_include_resolution_depth: 5 # Optional - Defaults to 20, maximum amount of levels to resolve includes
        # base_path: app_path         # Optional - Defaults to Current directory
        # destination: destination_in_data # Optional - Defaults to _data/contentful/spaces
        # individual_entry_files: true # Optional - Defaults to false
